Models/sale.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Mgmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id { get; set; }
        public string sale_prod { get; set; }
        public string sale_qnty { get; set; }
        public System.DateTime sale_date { get; set; }
    }
}

Controllers/SaleController.cs
using Inventory_Mgmt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory_Mgmt.Controllers
{
    public class SaleController : Controller
    {
        Inventory_mgmtEntities db = new Inventory_mgmtEntities();
        // GET: Sale
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DisplaySale()
        {
            List<sale> list = db.sales.OrderByDescending(x => x.id).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult SaleProduct()
        {
            List<string> list = db.products.Select(x => x.product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View();
        }

        [HttpPost]
        public ActionResult SaleProduct(sale s)
        {
            db.sales.Add(s);
            db.SaveChanges();
            return RedirectToAction("DisplaySale");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            sale s = db.sales.Where(x => x.id == id).SingleOrDefault();
            List<string> list = db.products.Select(x => x.product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View(s);
        }

        [HttpPost]
        public ActionResult Edit(int id, sale s)
        {
            sale sale = db.sales.Where(x => x.id == id).SingleOrDefault();
            sale.sale_prod=s.sale_prod;
            sale.sale_qnty=s.sale_qnty;
            sale.sale_date=s.sale_date;
            db.SaveChanges();
            return RedirectToAction("DisplaySale");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            sale s = db.sales.Where(x => x.id == id).SingleOrDefault();
            return View(s);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            sale s = db.sales.Where(x => x.id == id).SingleOrDefault();
            return View(s);
        }

        [HttpPost]
        public ActionResult Delete(int id, sale s)
        {
            db.sales.Remove(db.sales.Where(x => x.id == id).SingleOrDefault());
            db.SaveChanges();
            return RedirectToAction("DisplaySale");
        }
    }
}

Views/Sale/Delete.cshtml
@model Inventory_Mgmt.Models.sale

@{
    ViewBag.Title = "Delete Sale";
}

<div class="container mt-5">
    <div class="card border-danger shadow-sm">
        <div class="card-header bg-danger text-white text-center">
            <h3>Are you sure you want to delete this sale?</h3>
        </div>

        <div class="card-body">
            <h4 class="card-title text-center mb-4">Sale Details</h4>
            <dl class="row">
                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Sale Product")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.sale_prod)</p>
                </dd>

                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Sale Quantity")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.sale_qnty)</p>
                </dd>

                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Sale Date")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.sale_date)</p>
                </dd>
            </dl>
        </div>

        <div class="card-footer">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="row">
                    <div class="col-md-1">
                        <input type="submit" value="Delete" class="btn btn-outline-danger btn-block" />
                    </div>
                    <div class="col-md-1">
                        @Html.ActionLink("Cancel", "DisplaySale", "Sale", null, new { @class = "btn btn-outline-secondary btn-block" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Sale/Details.cshtml
@model Inventory_Mgmt.Models.sale

@{
    ViewBag.Title = "Sale Details";
}

<div class="container mt-5">
    <h2 class="text-center mb-4">Sale Details</h2>

    <div class="card shadow-sm">
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Sale Product")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.sale_prod)</p>
                </dd>

                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Sale Quantity")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.sale_qnty)</p>
                </dd>

                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Sale Date")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.sale_date)</p>
                </dd>
            </dl>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-1">
            @Html.ActionLink("Edit", "Edit", "Sale", new { id = Model.id }, new { @class = "btn btn-outline-primary btn-block" })
        </div>
        <div class="col-md-2">
            @Html.ActionLink("Back to List", "DisplaySale", "Sale", new { @class = "btn btn-outline-secondary btn-block" })
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Sale/DisplaySale.cshtml
@model IEnumerable<Inventory_Mgmt.Models.sale>

@{
    ViewBag.Title = "DisplaySale";
}

<p>
    @Html.ActionLink("Add New Sale", "SaleProduct", "Sale", new { }, new { @class = "btn btn-outline-primary btn-sm mx-1" })
</p>

<div class="container mt-5">
    <h2 class="text-center mb-4">Sale List</h2>
    <table class="table table-bordered table-light table-hover">
        <thead>
            <tr style="background-color: #f2f2f2; color: #333;">
                <th class="text-center" style="font-size: 18px; padding: 12px;">
                    @Html.DisplayName("Sale Product")
                </th>
                <th class="text-center" style="font-size: 18px; padding: 12px;">
                    @Html.DisplayName("Sale Quantity")
                </th>
                <th class="text-center" style="font-size: 18px; padding: 12px;">
                    @Html.DisplayName("Sale Date")
                </th>
                <th class="text-center" style="font-size: 18px; padding: 12px;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center align-middle">@Html.DisplayFor(modelItem => item.sale_prod)</td>
                        <td class="text-center align-middle">@Html.DisplayFor(modelItem => item.sale_qnty)</td>
                        <td class="text-center align-middle">@Html.DisplayFor(modelItem => item.sale_date)</td>
                        <td class="text-center align-middle">
                            <div class="d-flex justify-content-between">
                                <a href="@Url.Action("Edit", "Sale", new { id = item.id })" class="btn btn-outline-primary btn-sm w-100 mx-1">Edit</a>
                                <a href="@Url.Action("Details", "Sale", new { id = item.id })" class="btn btn-outline-success btn-sm w-100 mx-1">Details</a>
                                <a href="@Url.Action("Delete", "Sale", new { id = item.id })" class="btn btn-outline-danger btn-sm w-100 mx-1">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4" class="text-center">No sales available</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Sale/Edit.cshtml
@model Inventory_Mgmt.Models.sale

@{
    ViewBag.Title = "Edit Sale";
}

@section Scripts {
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.3.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
            });
        });
    </script>
}

<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white text-center">
            <h2>Update Sale</h2>
        </div>

        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                @Html.HiddenFor(model => model.id)

                <div class="form-group row">
                    @Html.Label("Sale Product", "Product", htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right font-weight-bold" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.sale_prod, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.sale_prod, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row mt-3">
                    @Html.Label("Sale Quantity", "Quantity", htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right font-weight-bold" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.sale_qnty, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.sale_qnty, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row mt-3">
                    @Html.Label("Sale Date", "Sale Date", htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right font-weight-bold" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.sale_date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.sale_date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row mt-4">
                    <div class="col-md-9 offset-md-3">
                        <button type="submit" class="btn btn-outline-primary btn-lg w-10">Update</button>
                    </div>
                </div>
            }
        </div>

        <div class="card-footer text-right">
            @Html.ActionLink("Back to List", "DisplaySale", null, new { @class = "btn btn-outline-danger btn-lg" })
        </div>
    </div>
</div>

Views/Sale/SaleProduct.cshtml
@model Inventory_Mgmt.Models.sale

@{
    ViewBag.Title = "SaleProduct";
}

@section Scripts {
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.3.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
            });
        });
    </script>
}

<h2 class="text-center mb-4">SaleProduct</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.sale_prod, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_prod, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.Label("Product Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_qnty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_qnty, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.Label("Sale Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <br />
                <input type="submit" value="Add" class="btn btn-outline-primary btn-sm mx-1" />
            </div>
        </div>
    </div>
}

<br />
<div>
    @Html.ActionLink("Back to List", "DisplaySale", null, new { @class = "btn btn-outline-secondary btn-sm mx-1" })
</div>