Controllers/PurchaseController.cs
using Inventory_Mgmt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory_Mgmt.Controllers
{
    public class PurchaseController : Controller
    {
        Inventory_mgmtEntities db = new Inventory_mgmtEntities();
        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DisplayPurchase()
        {
            List<purcahse> list = db.purcahses.OrderByDescending(x => x.id).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult PurchaseProduct()
        {
            List<string>list=db.products.Select(x=>x.product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View();
        }

        [HttpPost]
        public ActionResult PurchaseProduct(purcahse pr) 
        {
            db.purcahses.Add(pr);
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }

        [HttpGet]
        public ActionResult Edit(int id) 
        {
            purcahse p = db.purcahses.Where(x => x.id == id).SingleOrDefault();
            List<string> list = db.products.Select(x => x.product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View(p); 
        }

        [HttpPost]
        public ActionResult Edit(int id, purcahse pr)
        {
            purcahse pur= db.purcahses.Where(x => x.id == id).SingleOrDefault();
            pur.purchase_prod=pr.purchase_prod;
            pur.purchase_qnty=pr.purchase_qnty;
            pur.purchase_date=pr.purchase_date;
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }

        [HttpGet]
        public ActionResult PurchaseDetails(int id)
        {
            purcahse p = db.purcahses.Where(x => x.id == id).SingleOrDefault();
            List<string> list = db.products.Select(x => x.product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View(p);
        }

        [HttpGet]
        public ActionResult DeletePurchase(int id)
        {
            purcahse p = db.purcahses.Where(x => x.id == id).SingleOrDefault();
            return View(p);
        }

        [HttpPost]
        public ActionResult DeletePurchase(int id, purcahse pr)
        {
            db.purcahses.Remove(db.purcahses.Where(x => x.id == id).SingleOrDefault());
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }
    }

}

Views/Purchase/DeletePurchase.cshtml
@model Inventory_Mgmt.Models.purcahse

@{
    ViewBag.Title = "Delete Purchase";
}

<div class="container mt-5">
    <div class="card border-danger shadow-sm">
        <div class="card-header bg-danger text-white text-center">
            <h3>Are you sure you want to delete this purchase?</h3>
        </div>

        <div class="card-body">
            <h4 class="card-title text-center mb-4">Purchase Details</h4>
            <dl class="row">
                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Purchase Product")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.purchase_prod)</p>
                </dd>

                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Purchase Quantity")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.purchase_qnty)</p>
                </dd>

                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Purchase Date")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.purchase_date)</p>
                </dd>
            </dl>
        </div>

        <div class="card-footer">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="row">
                    <div class="col-md-1">
                        <input type="submit" value="Delete" class="btn btn-outline-danger btn-block" />
                    </div>
                    <div class="col-md-1">
                        @Html.ActionLink("Cancel", "DisplayPurchase", "Purchase", new { }, new { @class = "btn btn-outline-secondary btn-block" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Purchase/DisplayPurchase.cshtml
@model IEnumerable<Inventory_Mgmt.Models.purcahse>

@{
    ViewBag.Title = "DisplayPurchase";
}

<h6>Purchase List</h6>

<p>
    @Html.ActionLink("Add New Purchase", "PurchaseProduct", "Purchase", new { }, new { @class = "btn btn-outline-primary btn-sm mx-1" })
</p>

<div class="container mt-5">
    <h2 class="text-center mb-4">Purchase List</h2>
    <table class="table table-bordered table-light table-hover">
        <thead>
            <tr style="background-color: #f2f2f2; color: #333;">
                <th class="text-center" style="font-size: 18px; padding: 12px;">
                    @Html.DisplayName("Purchase Product")
                </th>
                <th class="text-center" style="font-size: 18px; padding: 12px;">
                    @Html.DisplayName("Purchase Quantity")
                </th>
                <th class="text-center" style="font-size: 18px; padding: 12px;">
                    @Html.DisplayName("Purchase Date")
                </th>
                <th class="text-center" style="font-size: 18px; padding: 12px;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center align-middle">@Html.DisplayFor(modelItem => item.purchase_prod)</td>
                        <td class="text-center align-middle">@Html.DisplayFor(modelItem => item.purchase_qnty)</td>
                        <td class="text-center align-middle">@Html.DisplayFor(modelItem => item.purchase_date)</td>
                        <td class="text-center align-middle">
                            <div class="d-flex justify-content-between">
                                <a href="@Url.Action("Edit", "Purchase", new { id = item.id })" class="btn btn-outline-primary btn-sm w-100 mx-1">Edit</a>
                                <a href="@Url.Action("PurchaseDetails", "Purchase", new { id = item.id })" class="btn btn-outline-success btn-sm w-100 mx-1">Details</a>
                                <a href="@Url.Action("DeletePurchase", "Purchase", new { id = item.id })" class="btn btn-outline-danger btn-sm w-100 mx-1">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4" class="text-center">No purchases available</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Purchase/Edit.cshtml
@model Inventory_Mgmt.Models.purcahse

@{
    ViewBag.Title = "Edit Purchase";
}

@section Scripts {
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.3.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
            });
        });
    </script>

}

<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white text-center">
            <h2>Update Purchase</h2>
        </div>

        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                @Html.HiddenFor(model => model.id)

                <div class="form-group row">
                    @Html.Label("Purchase Product", "Product", htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right font-weight-bold" })
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.purchase_prod, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.purchase_prod, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row mt-3">
                    @Html.Label("Purchase Quantity", "Quantity", htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right font-weight-bold" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.purchase_qnty, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.purchase_qnty, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row mt-3">
                    @Html.Label("Purchase Date", "Purchase Date", htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right font-weight-bold" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.purchase_date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.purchase_date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row mt-4">
                    <div class="col-md-9 offset-md-3">
                        <button type="submit" class="btn btn-outline-primary btn-lg w-10">Update</button>
                    </div>
                </div>
            }
        </div>

        <div class="card-footer text-right">
            @Html.ActionLink("Back to List", "DisplayPurchase", null, new { @class = "btn btn-outline-danger btn-lg" })
        </div>
    </div>
</div>

Views/Purchase/PurchaseDetails.cshtml
@model Inventory_Mgmt.Models.purcahse

@{
    ViewBag.Title = "Purchase Details";
}

<div class="container mt-5">
    <h2 class="text-center mb-4">Purchase Details</h2>

    <div class="card shadow-sm">
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Purchase Product")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.purchase_prod)</p>
                </dd>

                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Purchase Quantity")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.purchase_qnty)</p>
                </dd>

                <dt class="col-sm-4 text-right">
                    @Html.DisplayName("Purchase Date")
                </dt>
                <dd class="col-sm-8">
                    <p class="form-control-plaintext">@Html.DisplayFor(model => model.purchase_date)</p>
                </dd>
            </dl>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-1">
            @Html.ActionLink("Edit", "Edit", "Purchase", new { id = Model.id }, new { @class = "btn btn-outline-primary btn-block" })
        </div>
        <div class="col-md-2">
            @Html.ActionLink("Back to List", "DisplayPurchase", "Purchase", new { @class = "btn btn-outline-secondary btn-block" })
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Purchase/PurchaseProduct.cshtml
@model Inventory_Mgmt.Models.purcahse

@{
    ViewBag.Title = "PurchaseProduct";
}

@section Scripts {
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.3.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
            });
        });
    </script>

}

<h2 class="text-center mb-4">PurchaseProduct</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.purchase_prod, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.purchase_prod, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.Label("Product Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.purchase_qnty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.purchase_qnty, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.Label("Purchase Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.purchase_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.purchase_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <br />
                <input type="submit" value="Add" class="btn btn-outline-primary btn-sm  mx-1" />
            </div>
        </div>
    </div>
}
<br />
<div>
    @Html.ActionLink("Back to List", "DisplayPurchase", null, new { @class = "btn btn-outline-secondary btn-sm  mx-1" })
</div>